on: [push, pull_request]
name: Flatpak_test
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Git config  
      run: git config --global --add safe.directory /__w/shared_mem_random/shared_mem_random

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: test_shared-mem-random.flatpak
        manifest-path: network.koesling.test-shared-mem-random.yml
        cache-key: flatpak-builder-${{ github.sha }}
